# ============================================================
# AI Linux Health Assistant - Gemini API Connection Test
# ============================================================
# Purpose:
# This file tests whether our Python application can connect
# to the Gemini API and receive a response from an LLM.
#
# This is only a test. Later, we will replace the simple
# test question with our actual Linux health report.
# ============================================================


# ------------------------------------------------------------
# 1. Import the required libraries
# ------------------------------------------------------------

# 'os' allows Python to interact with environment variables.
# We will use it to retrieve our Gemini API key and model name.
import os

# 'load_dotenv' loads variables stored in our .env file
# so that Python can access them.
from dotenv import load_dotenv

# 'genai' is Google's Generative AI Python SDK.
# It allows our Python program to communicate with Gemini.
from google import genai


# ------------------------------------------------------------
# 2. Load environment variables from the .env file
# ------------------------------------------------------------

# Load the variables stored in our .env file.
#
# Our .env file contains configuration such as:
#
# GEMINI_API_KEY=our_secret_key
# GEMINI_MODEL=the_model_we_want_to_use
#
# We keep the API key outside our Python code so that
# the secret is not hard-coded into the program.
load_dotenv()


# ------------------------------------------------------------
# 3. Get Gemini configuration from the environment
# ------------------------------------------------------------

# os.getenv() retrieves the value of an environment variable.
#
# For example, if .env contains:
#
# GEMINI_MODEL=gemini-2.5-flash-lite
#
# then:
#
# model = os.getenv("GEMINI_MODEL")
#
# gives us:
#
# model = "gemini-2.5-flash-lite"

model = os.getenv("GEMINI_MODEL")

# Retrieve the Gemini API key from the environment.
#
# We NEVER print the API key because it is a secret.
api_key = os.getenv("GEMINI_API_KEY")
print("Model being used:", model)
print("API key configured:", api_key is not None)


# ------------------------------------------------------------
# 4. Create the Gemini client
# ------------------------------------------------------------

# Create a Gemini client using our API key.
#
# The client is the object our Python program will use
# to communicate with Google's Gemini API.
client = genai.Client(api_key=api_key)


# ------------------------------------------------------------
# 5. Send a request to Gemini
# ------------------------------------------------------------

# generate_content() sends our request to the Gemini model.
#
# 'model' tells Gemini which model should process our request.
#
# 'contents' contains the question/instruction that we
# want the LLM to answer.
#
# For now, we are using a simple test question.
#
# Later, we will replace this with information from:
#
# json/health_report.json
#
# so that Gemini can analyze our actual Linux health data.

interaction = client.interactions.create(
    model=model,
    input=(
        "Say hello and explain in one sentence "
        "what a Linux health monitoring system does."
    )
)

print(interaction.output_text)


# ------------------------------------------------------------
# 6. Display the LLM's response
# ------------------------------------------------------------

# response.text contains the text generated by Gemini.
#
# print() displays that response in our terminal.
print(interaction.output_text)